version: "3.7"


networks:
  traefik-public:
    external: true

volumes:
  blstimulator:

services:
  blstimulator:
    image: registry.dev.gbms.site/blstimulator
    volumes:
      - blstimulator:/data
    networks:
      - traefik-public
    environment:
      - APP_TELEGRAMBOT__TOKEN=${APP_TELEGRAMBOT__TOKEN?Variable not set}
      - APP_TELEGRAMBOT__URL=${APP_TELEGRAMBOT__URL?Variable not set}
      - APP_RABBITMQ__HOST=${APP_RABBITMQ__HOST?Variable not set}
      - APP_RABBITMQ__USER=${APP_RABBITMQ__USER?Variable not set}
      - APP_RABBITMQ__PASSWORD=${APP_RABBITMQ__PASSWORD?Variable not set}
      - APP_RABBITMQ__VHOST=${APP_RABBITMQ__VHOST?Variable not set}
    
    deploy:
      restart_policy:
        condition: on-failure
      mode: replicated
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.http.routers.blstimulator.rule=Host(`blstimulator.bl.gbms.site`)
        - traefik.http.routers.blstimulator-http.entrypoints=http
        - traefik.http.routers.blstimulator-http.service=blstimulator
        - traefik.http.routers.blstimulator-http.rule=Host(`blstimulator.bl.gbms.site`)
        - traefik.http.routers.blstimulator-http.middlewares=https-redirect
        - traefik.http.routers.blstimulator.entrypoints=https
        - traefik.http.routers.blstimulator.tls=true
        - traefik.http.routers.blstimulator.tls.certresolver=le
        - traefik.http.services.blstimulator.loadbalancer.server.port=80
        - traefik.http.routers.blstimulator.service=blstimulator