version: "3.9"

networks:
  traefik-public:
    external: true

volumes:
  blstimulator:

services:
  blstimulator:
    image: registry.dev.gbms.site/blstimulator
    volumes:
      - blstimulator:/data
    networks:
      - traefik-public
      - 
    deploy:
      restart_policy:
        condition: on-failure
      mode: replicated
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.http.routers.blstimulator.rule=Host(`blstimulator.bl.gbms.site`)
        - traefik.http.routers.blstimulator-http.entrypoints=http
        - traefik.http.routers.blstimulator-http.service=blstimulator
        - traefik.http.routers.blstimulator-http.rule=Host(`blstimulator.bl.gbms.site`)
        - traefik.http.routers.blstimulator-http.middlewares=https-redirect
        - traefik.http.routers.blstimulator.entrypoints=https
        - traefik.http.routers.blstimulator.tls=true
        - traefik.http.routers.blstimulator.tls.certresolver=le
        - traefik.http.services.blstimulator.loadbalancer.server.port=80
        - traefik.http.routers.blstimulator.service=blstimulator